from datetime import datetime, timezone

from sqlalchemy import JSON, DateTime, ForeignKey, Integer, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database.session import Base


class SavedRoadmap(Base):
    """
    A roadmap generated by POST /api/roadmap/generate, persisted for a
    logged-in user so GET /api/roadmap can return their most recent one.

    roadmap/projects/resources/skill_gap are stored as JSON blobs (the
    exact response shapes from the roadmap/skill-gap schemas) rather than
    being normalized into their own tables — a deliberate MVP tradeoff
    (requirement: "do not over-engineer the MVP").
    """

    __tablename__ = "saved_roadmaps"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    user_id: Mapped[int] = mapped_column(ForeignKey("users.id"), nullable=False, index=True)

    target_career: Mapped[str] = mapped_column(String(200), nullable=False)
    experience_level: Mapped[str] = mapped_column(String(50), nullable=False)

    skill_gap: Mapped[dict] = mapped_column(JSON, nullable=False)
    roadmap: Mapped[dict] = mapped_column(JSON, nullable=False)
    projects: Mapped[list] = mapped_column(JSON, nullable=False, default=list)
    resources: Mapped[list] = mapped_column(JSON, nullable=False, default=list)

    created_at: Mapped[datetime] = mapped_column(
        DateTime, default=lambda: datetime.now(timezone.utc), index=True
    )

    user = relationship("User", back_populates="roadmaps")
